// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/asn" | "/asn/[countryCode]" | "/asn/[countryCode]/[asn]" | "/changelog" | "/country" | "/country/[countryCode]" | "/docs" | "/docs/api/asn" | "/docs/api/countries" | "/docs/api/search" | "/docs/formats/cidr" | "/docs/formats/csv" | "/docs/formats/json" | "/docs/guides/asn-lookup" | "/docs/guides/export" | "/docs/guides/ip-lookup" | "/docs/installation" | "/docs/quick-start" | "/stats"
type PageRoutes = never
type LayoutRoutes = "/" | "/asn/[countryCode]" | "/asn/[countryCode]/[asn]" | "/country/[countryCode]" | "/docs"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/asn": {}
  "/asn/[countryCode]": { "countryCode": string; }
  "/asn/[countryCode]/[asn]": { "countryCode": string; "asn": string; }
  "/changelog": {}
  "/country": {}
  "/country/[countryCode]": { "countryCode": string; }
  "/docs": {}
  "/docs/api/asn": {}
  "/docs/api/countries": {}
  "/docs/api/search": {}
  "/docs/formats/cidr": {}
  "/docs/formats/csv": {}
  "/docs/formats/json": {}
  "/docs/guides/asn-lookup": {}
  "/docs/guides/export": {}
  "/docs/guides/ip-lookup": {}
  "/docs/installation": {}
  "/docs/quick-start": {}
  "/stats": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/asn/[countryCode]": never
  "/asn/[countryCode]/[asn]": never
  "/country/[countryCode]": never
  "/docs": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
