// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/asn/[countryCode]/[asn]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/asn/[countryCode]/[asn]">> = Specific
  const handler = {} as typeof import("../../app/asn/[countryCode]/[asn]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/asn/[countryCode]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/asn/[countryCode]">> = Specific
  const handler = {} as typeof import("../../app/asn/[countryCode]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/asn/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/asn">> = Specific
  const handler = {} as typeof import("../../app/asn/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/changelog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/changelog">> = Specific
  const handler = {} as typeof import("../../app/changelog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/country/[countryCode]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/country/[countryCode]">> = Specific
  const handler = {} as typeof import("../../app/country/[countryCode]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/country/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/country">> = Specific
  const handler = {} as typeof import("../../app/country/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/docs/api/asn/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/api/asn">> = Specific
  const handler = {} as typeof import("../../app/docs/api/asn/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/docs/api/countries/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/api/countries">> = Specific
  const handler = {} as typeof import("../../app/docs/api/countries/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/docs/api/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/api/search">> = Specific
  const handler = {} as typeof import("../../app/docs/api/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/docs/formats/cidr/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/formats/cidr">> = Specific
  const handler = {} as typeof import("../../app/docs/formats/cidr/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/docs/formats/csv/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/formats/csv">> = Specific
  const handler = {} as typeof import("../../app/docs/formats/csv/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/docs/formats/json/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/formats/json">> = Specific
  const handler = {} as typeof import("../../app/docs/formats/json/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/docs/guides/asn-lookup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/guides/asn-lookup">> = Specific
  const handler = {} as typeof import("../../app/docs/guides/asn-lookup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/docs/guides/export/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/guides/export">> = Specific
  const handler = {} as typeof import("../../app/docs/guides/export/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/docs/guides/ip-lookup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/guides/ip-lookup">> = Specific
  const handler = {} as typeof import("../../app/docs/guides/ip-lookup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/docs/installation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/installation">> = Specific
  const handler = {} as typeof import("../../app/docs/installation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs">> = Specific
  const handler = {} as typeof import("../../app/docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/docs/quick-start/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/quick-start">> = Specific
  const handler = {} as typeof import("../../app/docs/quick-start/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/stats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stats">> = Specific
  const handler = {} as typeof import("../../app/stats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/asn/[countryCode]/[asn]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/asn/[countryCode]/[asn]">> = Specific
  const handler = {} as typeof import("../../app/asn/[countryCode]/[asn]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/asn/[countryCode]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/asn/[countryCode]">> = Specific
  const handler = {} as typeof import("../../app/asn/[countryCode]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/country/[countryCode]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/country/[countryCode]">> = Specific
  const handler = {} as typeof import("../../app/country/[countryCode]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/docs/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/docs">> = Specific
  const handler = {} as typeof import("../../app/docs/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
