var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/changelog/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1slk6zt._.js")
R.c("server/chunks/ssr/node_modules_09r9c10._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_1f8_yls.js")
R.c("server/chunks/ssr/[root-of-the-server]__1ma_e7z._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1au0nys._.js")
R.c("server/chunks/ssr/_1et0yp6._.js")
R.c("server/chunks/ssr/app_not-found_tsx_1ez0193._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0p8s4lh._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_changelog_page_actions_1layjh4.js")
R.m(65872)
module.exports=R.m(65872).exports
